#!/bin/sh
#
# @name Gazebo x500 lidar gimbal
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_lidar_gimbal_explorer}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Disable preflight checks for multi-drone simulation
param set-default NAV_DLL_ACT 0
param set-default COM_RCL_EXCEPT 4
param set-default COM_ARM_WO_GPS 1

# Smoother tuning for stable takeoff behavior
param set-default MC_ROLL_P 6.0
param set-default MC_ROLLRATE_P 0.15
param set-default MC_ROLLRATE_I 0.05
param set-default MC_ROLLRATE_D 0.003

param set-default MC_PITCH_P 6.0
param set-default MC_PITCHRATE_P 0.15
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCHRATE_D 0.003

param set-default MC_YAW_P 2.8
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0.0

# Smoother position control for stable takeoff
param set-default MPC_XY_P 0.9
param set-default MPC_Z_P 1.0
param set-default MPC_XY_VEL_P_ACC 1.8
param set-default MPC_Z_VEL_P_ACC 4.0

# More conservative limits for smooth takeoff
param set-default MPC_XY_VEL_MAX 5.0
param set-default MPC_Z_VEL_MAX_UP 2.0
param set-default MPC_Z_VEL_MAX_DN 1.0
param set-default MPC_TILTMAX_AIR 15.0
param set-default MPC_TKO_SPEED 1.0

# Gimbal settings
param set-default MNT_MODE_IN 4
param set-default MNT_MODE_OUT 2
param set-default MNT_RC_IN_MODE 1

param set-default MNT_MAN_ROLL 1
param set-default MNT_MAN_PITCH 2
param set-default MNT_MAN_YAW 3

param set-default MNT_RANGE_ROLL 180
param set-default MNT_RANGE_PITCH 180
param set-default MNT_RANGE_YAW 720

# Additional GCS connection parameters for robustness
param set COM_DLL_EXCEPT 7
param set COM_DL_LOSS_T 60

# Battery simulation parameters to prevent warnings
param set-default SIM_BAT_MIN_PCT 80.0
param set-default SIM_BAT_DRAIN 300
param set-default COM_LOW_BAT_ACT 0

# EKF2 parameters for reliable position estimation
param set-default EKF2_REQ_GPS_H 0.1
param set-default EKF2_GPS_CHECK 0
param set-default EKF2_GPS_CTRL 7
param set-default EKF2_BARO_CTRL 1
param set-default EKF2_HGT_REF 0
